export const LOAD_SAMPLE_DATA = 'LOAD_SAMPLE_DATA'
export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
export const ADD_TO_ORDER = 'ADD_TO_ORDER'
